version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    restart: always
    networks:
      - vsap-networks
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    ports:
      - 9001:9000
      - 8000:8000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vsap-volumes:/data
    networks:
      - vsap-networks
  minio1:
    image: minio/minio:RELEASE.2021-05-22T02-34-39Z
    volumes:
      - vsap-volumes:/storage
    networks:
      - vsap-networks
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  audio-book:
    container_name: audio-book-api
    image: namnguyen2110/android:latest
    networks:
      - vsap-networks
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio1
networks:
  vsap-networks:
    driver: bridge
volumes:
  vsap-volumes:
