server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin
    url: jdbc:mariadb://40.90.168.71:3306/fonos?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
minio:
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: test
  default:
    folder: /
  url: http://40.90.168.71:9000
